#!/bin/bash

set -e

function restartTomcat {
  invoke-rc.d --quiet $1 restart || {
    RESULT=$?
    # Ignore if tomcat init script does not exist (yet)
    if [ $RESULT != 100 ]; then
      return $RESULT
    fi
  }
  return 0
}

if [ $1 = remove ]; then
  restartTomcat [[target.tomcat]]
fi
