#!/bin/sh

set -e

if [ "$1" = 1 ]
then
  # Initial installation, extract the original configuration
  unzip -qq -d /var/lib/phenotips/data/ /var/lib/phenotips/next/database-zip*.zip
  unzip -qq -d /var/lib/phenotips/data/solr/ /var/lib/phenotips/next/solr-config*.jar
else
  # Upgrade, update all Solr core configurations and only update specific Solr indexes
  unzip -q -d /var/lib/phenotips/next/solr /var/lib/phenotips/next/solr-config*.jar
  mv -t /var/lib/phenotips/data/solr/ /var/lib/phenotips/next/solr/solr.xml
  rm -rf /var/lib/phenotips/data/solr/hpo/ /var/lib/phenotips/data/solr/omim/ /var/lib/phenotips/data/solr/ethnicity/
  mv -t /var/lib/phenotips/data/solr/ /var/lib/phenotips/next/solr/hpo/ /var/lib/phenotips/next/solr/omim/ /var/lib/phenotips/next/solr/ethnicity
  if [[ -d /var/lib/phenotips/data/solr/patients/ ]]
  then
    rm -rf /var/lib/phenotips/data/solr/patients/conf/
    mv -t /var/lib/phenotips/data/solr/patients/ /var/lib/phenotips/next/solr/patients/conf/
  else
    mv -t /var/lib/phenotips/data/solr/ /var/lib/phenotips/next/solr/patients/
  fi
  # Deprecated core, remove
  rm -rf /var/lib/phenotips/data/solr/xwiki/
fi

# Cleanup
rm -rf /var/lib/phenotips/next/

# Reset proper rights
chown -R tomcat:tomcat /var/lib/phenotips/

# Increase the amount of heap memory allocated for Tomcat, if needed
if `cat /etc/tomcat6/tomcat6.conf | grep -E '^\s*JAVA_OPTS.*-Xmx' >/dev/null 2>&1`
then
  # There is a value for Xmx, check if it is large enough
  CURRENT=`cat /etc/tomcat6/tomcat6.conf | grep -E '^\s*JAVA_OPTS.*-Xmx' | sed -r -e 's/^\s*JAVA_OPTS.*-Xmx([^" ]+).*/\1/'`
  echo $CURRENT | grep -i g >/dev/null 2>&1 && CURRENT=`echo ${CURRENT}\*1024*1024*1024 | sed -e 's/[gG]//' | bc`
  echo $CURRENT | grep -i m >/dev/null 2>&1 && CURRENT=`echo ${CURRENT}\*1024*1024 | sed -e 's/[mM]//' | bc`
  echo $CURRENT | grep -i k >/dev/null 2>&1 && CURRENT=`echo ${CURRENT}\*1024 | sed -e 's/[kK]//' | bc`
  if [ "`echo "$CURRENT > 1073741823" | bc`" = "0" ]
  then
    # Not large enough, update the value in place
    sed -i -r -e 's/^(\s*JAVA_OPTS.*-Xmx)([^" ]+)(.*)/\11g\3/' /etc/tomcat6/tomcat6.conf
  fi
elif `cat /etc/tomcat6/tomcat6.conf | grep -E '^\s*JAVA_OPTS=' >/dev/null 2>&1`
then
  # No Xmx configured, but there is a JAVA_OPTS setting, update it
  sed -i -r -e 's/^(\s*JAVA_OPTS=")(.*)/\1-Xmx1g \2/' /etc/tomcat6/tomcat6.conf
else
  # No JAVA_OPTS setting, add one with both Xmx and MaxPermSize
  echo -e -n '\nJAVA_OPTS="-Xmx1g -XX:MaxPermSize=192m"' >> /etc/tomcat6/tomcat6.conf
fi

# Increase the amount of permgen memory allocated for Tomcat, if needed
if `cat /etc/tomcat6/tomcat6.conf | grep -E '^\s*JAVA_OPTS.*-XX:MaxPermSize=' >/dev/null 2>&1`
then
  # There is a value for MaxPermSize, check if it is large enough
  CURRENT=`cat /etc/tomcat6/tomcat6.conf | grep -E '^\s*JAVA_OPTS.*-XX:MaxPermSize=' | sed -r -e 's/^\s*JAVA_OPTS.*-XX:MaxPermSize=([^" ]+).*/\1/'`
  echo $CURRENT | grep -i g >/dev/null 2>&1 && CURRENT=`echo ${CURRENT}\*1024*1024*1024 | sed -e 's/[gG]//' | bc`
  echo $CURRENT | grep -i m >/dev/null 2>&1 && CURRENT=`echo ${CURRENT}\*1024*1024 | sed -e 's/[mM]//' | bc`
  echo $CURRENT | grep -i k >/dev/null 2>&1 && CURRENT=`echo ${CURRENT}\*1024 | sed -e 's/[kK]//' | bc`
  if [ "`echo "$CURRENT > 201326591" | bc`" = "0" ]
  then
    # Not large enough, update the value in place
    sed -i -r -e 's/^(\s*JAVA_OPTS.*-XX:MaxPermSize=)([^" ]+)(.*)/\1192m\3/' /etc/tomcat6/tomcat6.conf
  fi
elif `cat /etc/tomcat6/tomcat6.conf | grep -E '^\s*JAVA_OPTS=' >/dev/null 2>&1`
then
  # No MaxPermSize configured, but there is a JAVA_OPTS setting, update it
  sed -i -r -e 's/^(\s*JAVA_OPTS=")(.*)/\1-XX:MaxPermSize=192m \2/' /etc/tomcat6/tomcat6.conf
fi

# Start Tomcat
if [[ -a /etc/init.d/tomcat6 ]]
then
  /sbin/service tomcat6 start >/dev/null 2>&1 || true
fi